define([], function () {
  return {
    "PropertyPaneDescription": "Description",
    "BasicGroupName": "Site name",
    "DescriptionFieldLabel": "Description field",

    "CreateSiteButton": "Create Site",
    "CreateSiteTitle": "Create a new Site",

    "OwningDepartmentDisplayName": "Owning department: *",

    "NewActivity": "New Activity and Service",
    "ActivityResponsible": "Responsible",
    "ActivityName": "Name",
    "ActivityDescription": "Description",
    "OpenForExternalSharing": "Open for external sharing?",
    "Cancel": "Cancel",
    "Finish": "Finish",
    "IncompleteAlert": "Please fill in all the required fields",

    "NewDepartment": "New department",
    "DepartmentLeader": "Leader",
    "DepartmentName": "Name",
    "Description": "Description",
    "ShortName": "Short name",

    "Section": "Section",
    "NewSection": "New section",

    "ChooseType": "Choose the type of site you want to create",
    "Activity": "Activity and Service",
    "Department": "Department",
    "Project": "Project",

    "GroupOrderedSuccesfullyDialog": "The site has been ordered",
    'GroupOrderedSuccesfullyDialogSub': 'Click "Finish" to proceed.',
    "SomethingWentWrong": "Something went wrong, please contact your IT-department",

    "ChooseParentDepartment": "Choose parent department",
    "ParentDepartment": "Parent department:",

    "SuggestedPeople": "Suggestions",
    "NoResultsFound": "No results found",
    "Loading": "Loading",

    "PrivacySetting": "Privacy settings",
    "PrivacyPublic": "Public - anyone in the organization can access this site",
    "PrivacyPrivate": "Private - only members can access this site",

    "January": "January",
    "February": "February",
    "March": "March",
    "April": "April",
    "May": "May",
    "June": "June",
    "July": "July",
    "August": "August",
    "September": "September",
    "October": "October",
    "November": "November",
    "December": "December",
    "Jan": "Jan",
    "Feb": "Feb",
    "Mar": "Mar",
    "Apr": "Apr",
    "MayMonth": "May",
    "Jun": "Jun",
    "Jul": "Jul",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "Nov",
    "Dec": "Dec",
    "Monday": "Monday",
    "Tuesday": "Tuesday",
    "Wednesday": "Wednesday",
    "Thirsday": "Thirsday",
    "Friday": "Friday",
    "Saturday": "Saturday",
    "Sunday": "Sunday",
    "ShortMonday": "M",
    "ShortTuesday": "T",
    "ShortWednesday": "W",
    "ShortThirsday": "T",
    "ShortFriday": "F",
    "ShortSaturday": "S",
    "ShortSunday": "S",
    "goToToday": "go to today",
    "prevMonthAriaLabel": "go to previous month",
    "nextMonthAriaLabel": "go to next month",
    "prevYearAriaLabel": "go to previous year",
    "nextYearAriaLabel": "go to next year",


    "NewProject": "New Project",
    "ProjectName": "Project name",
    "ProjectLeader": "Project manager (internal)",
    "ProjectGoal": "Project goal",
    "ProjectPurpose": "Project purpose",
    "ProjectNumber": "Project number",
    "NoProjectNumber": "There is no project number",
    "PreferedURL": "Prefered URL",
    "SiteAddress": "Site address",
    "StartDate": "Start date",
    "EndDate": "End date",

    "TypeHerePlaceholder": "Type here to search",
    "PropertyPaneDepartmentSiteTypeName": "'Avdeling' site type name:",
    "PropertyPaneHideParentDepartment": "Hide the field 'Parent department' field"
  }
});