define([], function () {
    return {
        "PropertyPaneDescription": "Beskrivelse",
        "BasicGroupName": "Område navn",
        "DescriptionFieldLabel": "Beskrivelse felt",

        "CreateSiteButton": "Bestill område",
        "CreateSiteTitle": "Bestill et nytt område",

        "OwningDepartmentDisplayName": "Avdelingstilhørlighet: *",

        "NewActivity": "Ny Aktivitet og Tjeneste",
        "ActivityResponsible": "Ansvarlig",
        "ActivityName": "Navn",
        "ActivityDescription": "Beskrivelse",
        "OpenForExternalSharing": "Åpen for ekstern deling",
        "CreateMicrosoftTeam": "Opprett Microsoft Team",
        "Cancel": "Avbryt",
        "Finish": "Fullfør",
        "IncompleteAlert": "Vennligst fyll inn alle obligatoriske felter",

        "NewDepartment": "Ny Avdeling",
        "DepartmentLeader": "Leder",
        "DepartmentName": "Navn",
        "Description": "Beskrivelse",
        "ShortName": "Kort navn",

        "Section": "Seksjon",
        "NewSection": "Ny seksjon",

        "ChooseType": "Velg hvilken type område du vil bestille",
        "Activity": "Aktivitet og Tjeneste",
        "Department": "Avdeling",
        "Project": "Prosjekt",

        "GroupOrderedSuccesfullyDialog": "Området er bestillt",
        'GroupOrderedSuccesfullyDialogSub': 'Klikk "Fullfør" for å fortsette.',
        "SomethingWentWrong": "Noe gikk galt, vennligst ta kontakt med IT-avdelingen",

        "ChooseParentDepartment": "Velg overordnet avdeling",
        "ParentDepartment": "Overordnet avdeling:",

        "SuggestedPeople": "Forslag",
        "NoResultsFound": "Ingen resultater",
        "Loading": "Laster",

        "PrivacySetting": "Personverninnstillinger",
        "PrivacyPublic": "Offentlig – alle i organisasjonen har tilgang til dette området",
        "PrivacyPrivate": "Privat – bare medlemmer har tilgang til dette området",

        "January": "Januar",
        "February": "Februar",
        "March": "Mars",
        "April": "April",
        "May": "Mai",
        "June": "Juni",
        "July": "Juli",
        "August": "August",
        "September": "September",
        "October": "Oktober",
        "November": "November",
        "December": "Desember",
        "Jan": "Jan",
        "Feb": "Feb",
        "Mar": "Mar",
        "Apr": "Apr",
        "MayMonth": "Mai",
        "Jun": "Jun",
        "Jul": "Jul",
        "Aug": "Aug",
        "Sep": "Sep",
        "Oct": "Okt",
        "Nov": "Nov",
        "Dec": "Des",
        "Monday": "Mandag",
        "Tuesday": "Tirsdag",
        "Wednesday": "Onsdag",
        "Thirsday": "Torsdag",
        "Friday": "Fredag",
        "Saturday": "Lørdag",
        "Sunday": "Søndag",
        "ShortMonday": "M",
        "ShortTuesday": "T",
        "ShortWednesday": "O",
        "ShortThirsday": "T",
        "ShortFriday": "F",
        "ShortSaturday": "L",
        "ShortSunday": "S",
        "goToToday": "go til i dag",
        "prevMonthAriaLabel": "gå til forrige måned",
        "nextMonthAriaLabel": "gå til neste måned",
        "prevYearAriaLabel": "gå til forrige år",
        "nextYearAriaLabel": "gå til neste år",


        "NewProject": "Nytt Prosjekt",
        "ProjectName": "Prosjektnavn",
        "ProjectLeader": "Prosjektleder (intern)",
        "ProjectGoal": "Prosjektmål",
        "ProjectPurpose": "Prosjektformål",
        "ProjectNumber": "Prosjektnummer",
        "NoProjectNumber": "Det finnes ingen prosjektnummer",
        "PreferedURL": "Ønsket URL",
        "SiteAddress": "Nettsted adresse",
        "StartDate": "Startdato",
        "EndDate": "Sluttdato",

        "TypeHerePlaceholder": "Skriv her for å søke",
        "PropertyPaneDepartmentSiteTypeName": "Navn på områdetypen 'Avdeling':",
        "PropertyPaneHideParentDepartment": "Skjul feltet 'Overordnet avdeling'"
    }
});
