define([], function () {
    return {
        "PropertyPaneDescription": "Beskrivelse",
        "BasicGroupName": "Område navn",
        "DescriptionFieldLabel": "Beskrivelse felt",
        "OrderSiteURLLabel": "orderSiteURL",
        "editName": "rediger navn",
        "editDescription": "rediger beskrivelse",
        "editProjectGoal": "rediger prosjekt mål",
        "editProjectPurpose": "rediger prosjekt formål",
        "editOwner": "rediger eier",
        "editShortName": "rediger kort navn",
        "editParentDepartment": "rediger overordnet avdeling",
        "editOwningDepartment": "rediger avdelingstilhørlighet",
        "editProjectNumber": "rediger prosjekt nummer",
        "editStartDate": "rediger start dato",
        "editEndDate": "rediger slutt dato",

        "CreateSiteButton": "Bestill område",
        "CreateSiteTitle": "Bestill en ny område",

        "OwningDepartmentDisplayName": "Avdelingstilhørlighet",

        "NewActivity": "Ny Aktivitet",
        "ActivityResponsible": "Ansvarlig",
        "ActivityName": "Navn",
        "ActivityDescription": "Beskrivelse",
        "OpenForExternalSharing": "Åpen for ekstern deling?",
        "Cancel": "Avbryt",
        "Finish": "Fullfør",
        "Save": "Lagre",
        "ok": "OK",
        "IncompleteAlert": "Vennligst fyll inn alle obligatoriske felter",

        "NewDepartment": "Ny Avdeling",
        "DepartmentLeader": "Leder",
        "DepartmentName": "Navn",
        "Description": "Beskrivelse",
        "ShortName": "Kort navn",

        "ChooseType": "Velg hvilken type område du vil bestille",
        "Activity": "Aktivitet",
        "Department": "Avdeling",
        "Project": "Prosjekt",
        "Group": "Gruppe",

        "GroupOrderedSuccesfullyDialog": "Gruppen er bestillt",
        'GroupOrderedSuccesfullyDialogSub': 'Klikk "Fullfør" for å fortsette.',
        "GroupSavedSuccesfullyDialog": "Gruppen har blitt lagret",
        'GroupSavedSuccesfullyDialogSub': 'Klikk "Fullfør" for å fortsette.',
        "SomethingWentWrong": "Noe gikk galt, vennligst ta kontakt med IT-avdelingen",

        "ChooseParentDepartment": "Velg overordnet avdeling",
        "ParentDepartment": "Overordnet avdeling",

        "SuggestedPeople": "Forslag",
        "NoResultsFound": "Ingen resultater",
        "Loading": "Laster",

        "PrivacySetting": "Personverninnstrillinger",
        "PrivacyPublic": "Offentlig – alle i organisasjonen har tilgang til dette området",
        "PrivacyPrivate": "Privat – bare medlemmer har tilgang til dette området",

        "January": "Januar",
        "February": "Februar",
        "March": "Mars",
        "April": "April",
        "May": "Mai",
        "June": "Juni",
        "July": "Juli",
        "August": "August",
        "September": "September",
        "October": "Oktober",
        "November": "November",
        "December": "Desember",
        "Jan": "Jan",
        "Feb": "Feb",
        "Mar": "Mar",
        "Apr": "Apr",
        "MayMonth": "Mai",
        "Jun": "Jun",
        "Jul": "Jul",
        "Aug": "Aug",
        "Sep": "Sep",
        "Oct": "Okt",
        "Nov": "Nov",
        "Dec": "Des",
        "Monday": "Mandag",
        "Tuesday": "Tirsdag",
        "Wednesday": "Onsdag",
        "Thirsday": "Torsdag",
        "Friday": "Fredag",
        "Saturday": "Lørdag",
        "Sunday": "Søndag",
        "ShortMonday": "M",
        "ShortTuesday": "T",
        "ShortWednesday": "O",
        "ShortThirsday": "T",
        "ShortFriday": "F",
        "ShortSaturday": "L",
        "ShortSunday": "S",
        "goToToday": "go til i dag",
        "prevMonthAriaLabel": "gå til forrige måned",
        "nextMonthAriaLabel": "gå til neste måned",
        "prevYearAriaLabel": "gå til forrige år",
        "nextYearAriaLabel": "gå til neste år",


        "NewProject": "Nytt Prosjekt",
        "ProjectName": "Prosjektnavn",
        "ProjectLeader": "Prosjektleder",
        "ProjectGoal": "Prosjektmål",
        "ProjectPurpose": "Prosjekt formål",
        "ProjectNumber": "Prosjekt nummer",
        "NoProjectNumber": "Det finnes ingen prosjekt nummer",
        "PreferedURL": "Ønsket URL",
        "SiteAddress": "Nettsted adresse",
        "StartDate": "Startdato",
        "EndDate": "Sluttdato",

        "TypeHerePlaceholder": "Skriv her for å søke",
        "informationAbout": "Informasjon om",
        "siteTypeActivity": "aktiviteten eller tjenesten",
        "siteTypeDepartment": "avdelingen",
        "siteTypeProject": "prosjektet",
        "siteTypeSection": "seksjonen",
        "siteTypeGroup": "gruppen"
    }
});