define([], function() {
  return {
    "PropertyPaneDescription": "A searchable, sortable and filterable list of Office 365 groups.",
    "BasicGroupName": "General settings",
    "DescriptionFieldLabel": "List rows per page",
    "SchemaName": "extvcs569it_InmetaGenericSchema",
    "Title": "Title",
    "SiteType": "Site type",
    "ProjectManager": "Project manager",
    "DepartmentManager": "Department manager",
    "Manager": "Responsible",
    "Department": "Department",
    "Mail": "Site email",
    "New": "New",
    "SendEmailTo": "Send an email to {0}",
    "StartChatWith": "Start a chat with {0}",
    "Contact": "Contact",
    "UpdateProfile": "Update your profile",
    "LoadingGroups": "Loading sites, please wait.",
    "WebPartTitle": "Site catalog",
    "NoGroupsFound": "No sites found.",
    "SearchPlaceHolder": "Search",
    "SortAsc": "Ascending",
    "SortDesc": "Descending",
    "Next": "Next",
    "Back": "Previous",
    "Calendar": "Calendar",
    "Email": "Email",
    "Planner": "Planner",
    "Sharepoint": "Sharepoint",
    "ShowNewButtonLabel": "Show the New-button in toolbar, allowing users to create new sites.",
    "PropertyPaneSiteTypes": "A comma seperated list of possible site types. E.g. (Aktivitet,Seksjon,Prosjekt)",
    "PropertyPaneHideParentDepartment": "Hide 'Department' column",
    "PropertyPaneSearchSetting": "Search settings",
    "PropertyPaneSearchType": "Graph filter search: Choose this if you have more than 999 groups in your organization. Only supports 'starts with' search method. Javascript search: Choose this if you have less than 999 groups in your organization. Supports 'contains' search method.",
    "PropertyPaneSearchTypeGraph": "Graph filter search",
    "PropertyPaneSearchTypeJavascript": "Javascript search"
  }
});