define([], function() {
  return {
    "PropertyPaneDescription": "En søk-, sorter-, og filtrerbar liste over Office 365 grupper.",
    "BasicGroupName": "Generelle instillinger",
    "DescriptionFieldLabel": "Antall rader per side",
    "SchemaName": "extvcs569it_InmetaGenericSchema",
    "Title": "Tittel",
    "SiteType": "Områdetype",
    "ProjectManager": "Prosjektleder",
    "DepartmentManager": "Avdelingsleder",
    "Manager": "Ansvarlig",
    "Department": "Avdeling",
    "Mail": "E-post",
    "New": "Opprett",
    "SendEmailTo": "Send en e-post til {0}",
    "StartChatWith": "Start en chat med {0}",
    "Contact": "Kontakt",
    "UpdateProfile": "Oppdater din profil",
    "LoadingGroups": "Laster inn områder, vennligst vent.",
    "WebPartTitle": "Områdekatalog",
    "NoGroupsFound": "Fant ingen områder.",
    "SearchPlaceHolder": "Søk",
    "SortAsc": "Stigende",
    "SortDesc": "Synkende",
    "Next": "Neste",
    "Back": "Forrige",
    "Calendar": "Kalender",
    "Email": "E-post",
    "Planner": "Planner",
    "Sharepoint": "Sharepoint",
    "ShowNewButtonLabel": "Vis 'Ny'-knappen, som lar brukere opprette nye områder.",
    "PropertyPaneSiteTypes": "En komma separert liste av mulige sidetyper. F.eks. (Aktivitet,Seksjon,Prosjekt)",
    "PropertyPaneHideParentDepartment": "Skjul kolonnen 'Avdeling'",
    "PropertyPaneSearchSetting": "Insillinger for søk",
    "PropertyPaneSearchType": "Graph filter søk: Velg denne hvis du har flere enn 999 grupper i organisasjonen. Støtter kun 'starts with' søke-metode. Javascript søk: Velg denne hvis du har færre enn 999 grupper i organisasjonen. Støtter 'contains' søke-metode.",
    "PropertyPaneSearchTypeGraph": "Graph filter søk",
    "PropertyPaneSearchTypeJavascript": "Javascript søk"
  }
});